import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/NavBar";
import Footer from "@/components/common/Footer";
import { Toaster } from "react-hot-toast";
import ScrollToTop from "@/components/common/ScrollToTop";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <Navbar />
         {/* ← Put Toaster here – appears on top of everything */}
        <Toaster
          position="top-center" // or "top-right", "bottom-right", etc.
          toastOptions={{
            duration: 5000,
            style: {
              borderRadius: "10px",
              background: "#333",
              color: "#fff",
              maxWidth: "500px",
            },
            success: {
              style: {
                background: "#10b981", // green
                color: "white",
              },
              iconTheme: {
                primary: "white",
                secondary: "#10b981",
              },
            },
            error: {
              style: {
                background: "#ef4444", // red
                color: "white",
              },
            },
          }}
        />
        {children}
        <Footer />
        <ScrollToTop />
        </body>
    </html>
  );
}
